# -*- coding: utf-8 -*-
"""E11 Shutff

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1315EnyX7-p7ANr8lYM5EB049GA10Tig3
"""

# Measures Temperature, Humidty, Pressure
# BME280 - Adafruit

import time
from Adafruit_BME280 import *

sensor = BME280(t_mode=BME280_OSMAPLE_8, p_mode=BME280, h_mode=BME280)

times = []
temperatures = []
pressure = []
humidity = []

start_time = time.time()
stop_time = start_time + 5*60
current_time = time.time()

while current_time < stop_time:
  temp = sensor.read_temperature()
  current_time = time.time()
  print(temp)
  times.append(current_time)
  temperatures.append(temp)
  time.sleep(1)

# Write the data to a file - time column, temperature, humidity, pressure
# Look up Adafruit CircuitPython BME280 module 
# update code to use module

import csv
import time
from Adafruit_BME280 import *

header = ['Time','Temperature','Pressure','Humidity']
sensor = BME280(t_mode=BME280_OSMAPLE_8, p_mode=BME280, h_mode=BME280)

times = []
temperatures = []
pressure = []
humidity = []

start_time = time.time()
stop_time = start_time + 5*60
current_time = time.time()

while current_time < stop_time:
  temp = sensor.read_temperature()
  press = sensor.read_pressure()
  humid = sensor.read.humidity()
  current_time = time.time()
  with open('SensorData.csv','w') as f
    writer = csv.writer(f)
    writer.write(header)
    writer.writerow(['current_time','temp','press','humid'])
  print(temp)
  times.append(current_time)
  temperatures.append(temp)
  pressure.append(press)
  humidity.append(humid)
  time.sleep(1)